version: '3.3'
services:
  db:
    image: web-mongo:latest
    volumes:
      - /gdw/database/mongodb:/var/lib/mongodb
    environment: 
      - MONGODB=mongodb://${MONGO_USER}:${MONGO_USER_PASSWORD}@db:${MONGO_PORT}/${MONGO_DATABASE_NAME}?authSource=${MONGO_DATABASE_NAME}&authMechanism=${MONGO_AUTH_MECHANISM}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_USER_PASSWORD=${MONGO_USER_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
    restart: always
    ports: 
      - "27017:27017"
  web:
    image: web-backend:latest
    command: gunicorn --timeout 120 --bind 0.0.0.0:5000 app:app
    ports: 
      - 8080:5000
    environment:
      - MONGODB=mongodb://${MONGO_USER}:${MONGO_USER_PASSWORD}@db:${MONGO_PORT}/${MONGO_DATABASE_NAME}?authSource=${MONGO_DATABASE_NAME}&authMechanism=${MONGO_AUTH_MECHANISM}
    volumes:
      - /gdw/tmp/:/temp
    depends_on: 
      - db