version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports: 
      - 5000:5000
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_USER_PASSWORD=${MONGO_USER_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - MONGO_AUTH_MECHANISM=${MONGO_AUTH_MECHANISM}
    volumes:
      - /tfg/tmp/:/app/temp